export const VALIDITY_CODES = {
  MISSING_DATA: "MISSING_DATA",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  FAST_RTS: "FAST_RTS",
  NON_ENGAGED: "NON_ENGAGED",
  SST_NONCOMPLIANT: "SST_NONCOMPLIANT",
  SJT_LOW: "SJT_LOW",
  RB_LOW: "RB_LOW",
  DD_STEEP: "DD_STEEP"
};
